FROM debian:11
RUN rm -rf /var/lib/apt/lists/*
RUN DEBIAN_FRONTEND=noninteractive \
 apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get -y install ssh openssh-server python3 net-tools passwd bash-completion dos2unix wget python3-requests python3-dev \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cdbs devscripts equivs fakeroot
RUN mkdir /var/run/sshd
RUN echo 'root:Ash82qc44L6ZVv' | chpasswd
RUN sed -i 's|#PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin yes|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PasswordAuthentication yes|PasswordAuthentication yes|' "/etc/ssh/sshd_config"
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
