FROM centos:7
RUN yum -y update
RUN yum -y install nano openssh-server net-tools passwd bash-completion dos2unix wget
RUN yum -y install @core
RUN mkdir /var/run/sshd
RUN chkconfig sshd on
RUN echo 'root:Ash82qc44L6ZVv' | chpasswd
RUN sed -i 's|#PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin yes|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PasswordAuthentication yes|PasswordAuthentication yes|' "/etc/ssh/sshd_config"
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_dsa_key -N ''
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_ed25519_key -N ''
RUN sed -i 's|Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin|Defaults    secure_path = /usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin|' /etc/sudoers
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]

