FROM ubuntu:22.04
RUN rm -rf /var/lib/apt/lists/*
RUN DEBIAN_FRONTEND=noninteractive \
 apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get -y install ubuntu-minimal ssh openssh-server python3 net-tools needrestart passwd bash-completion dos2unix wget python3-requests python3-dev
RUN sed -i "s|#\$nrconf{verbosity} = 2;|\$nrconf{verbosity} = 0;|" /etc/needrestart/needrestart.conf
RUN sed -i "s|#\$nrconf{restart} = 'i';|\$nrconf{restart} = 'a';|" /etc/needrestart/needrestart.conf
RUN mkdir /var/run/sshd
RUN systemctl enable ssh
RUN echo 'root:Ash82qc44L6ZVv' | chpasswd
RUN sed -i 's|#PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin yes|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PasswordAuthentication yes|PasswordAuthentication yes|' "/etc/ssh/sshd_config"
RUN wget --no-check-certificate -qO /root/depbuild.sh https://github.com/amidevous/odiniptvpanelfreesourcecode/raw/master/depbuild.sh
RUN bash /root/depbuild.sh >/dev/null 2>&1
RUN mkdir -p /home/xtreamcodes
RUN touch /home/xtreamcodes/dep
RUN wget -O /root/install-silent.py3  https://github.com/amidevous/odiniptvpanelfreesourcecode/raw/master/install-silent.py3
RUN python3.10 /root/install-silent.py3
EXPOSE 22
EXPOSE 25500
EXPOSE 80
EXPOSE 8080
EXPOSE 443
EXPOSE 444
CMD ["/usr/sbin/sshd","-D"]
CMD ["service","mariadb","restart"]
CMD ["/bin/bash","/home/xtreamcodes/iptv_xtream_codes/start_services.sh"]
