FROM ubuntu:12.04
RUN echo "deb http://old-releases.ubuntu.com/ubuntu/ precise main restricted universe multiverse" > /etc/apt/sources.list
RUN echo "deb-src http://old-releases.ubuntu.com/ubuntu/ precise main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://old-releases.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb-src http://old-releases.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://old-releases.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb-src http://old-releases.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse" >> /etc/apt/sources.list
RUN rm -rf /var/lib/apt/lists/*
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install ssh openssh-server
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install net-tools
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install passwd
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install bash-completion
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install dos2unix
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install wget
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install cdbs
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install devscripts
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install equivs
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install fakeroot
RUN mkdir /var/run/sshd
RUN echo 'root:Ash82qc44L6ZVv' | chpasswd
RUN sed -i 's|#PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin no|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin yes|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|PermitRootLogin prohibit-password|PermitRootLogin yes|' "/etc/ssh/sshd_config"
RUN sed -i 's|#PasswordAuthentication yes|PasswordAuthentication yes|' "/etc/ssh/sshd_config"
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
